version: '3.3'

services:
    convo-service:
        image: convo-service
        build: .
        ports:
            - '80:5000'
        # volumes:
        #   - './node_modules:/app/node_modules'
        #   - './src:/app/src'
        restart: on-failure
        # logging: *default-logging
        # logging: *default-logging